/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Shipping.gltf 
*/

import React, { useEffect } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations, useTexture, Text } from '@react-three/drei'
import * as THREE from 'three'
import vara from './public/Textures/Vara.jpg'
import whatsapp from './src/assets/whatsapp.png'
import instagram from './src/assets/Instagram.png'
import linkedIn from './src/assets/LinkedIn.png'
import github from './src/assets/github.png'
import { useFrame } from '@react-three/fiber'
export default function Shipping(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Shipping.gltf')
  const { actions } = useAnimations(animations, group)
  console.log(actions)
  useEffect(()=>{
    actions.SphereAction.play();
    actions.Links.play();
  })
  useFrame(()=>{
    group.current.rotation.y+=0.001;
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" scale={[3,3,3]} rotation={[-Math.PI/5,Math.PI/2,0]}>
        <group name="Point" rotation={[-Math.PI / 2, 0, 0]} />
        <pointLight name="Light" intensity={1000.413} decay={2} position={[3.076, 1.904, 1.005]} rotation={[-1.839, 0.602, 0.932]} />
        <ambientLight intensity={0.5}/>
        <Text position={[1,2,0]} rotation={[0,-Math.PI/2,0]} scale={[0.3,0.3,0.3]}>Contact me!!</Text>
        <PerspectiveCamera name="Camera" makeDefault={false} far={100} near={0.1} fov={22.895} position={[7.359, 4.958, 6.926]} rotation={[-0.627, 0.71, 0.441]} />
        <group name="Sphere" rotation={[0.192, 2, 0]}>
          <mesh name="Sphere_1" geometry={nodes.Sphere_1.geometry} material={new THREE.MeshStandardMaterial({color:'lightblue',metalness:1})} />
          <mesh name="Sphere_2" geometry={nodes.Sphere_2.geometry} material={new THREE.MeshStandardMaterial({color:'brown',metalness:1})} />
          <mesh name="Sphere_3" geometry={nodes.Sphere_3.geometry} material={new THREE.MeshStandardMaterial({color:'white',metalness:1,emissiveIntensity:1})}/>
          <mesh name="Sphere_4" geometry={nodes.Sphere_4.geometry} material={new THREE.MeshStandardMaterial({color:'white',metalness:1,emissiveIntensity:1})} />
        </group>
        <group name="Plane" position={[-0.01, 0.82, 0.01]} rotation={[2.214,3.05, 1.623]} scale={[0.46, 1.15, 0.38]}>
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={new THREE.MeshStandardMaterial({map:useTexture(vara)})} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['Material.002']} />
          <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials['Material.003']} />
        </group>
        <mesh name="Text" geometry={nodes.Text.geometry} material={materials['Material.004']} position={[0.933, 0.707, 0.501]} rotation={[1.645, 0.053, -1.432]} scale={[0.239, 0.363, 0.343]} />
        <group name="Plane001" position={[-1.698, 0.066, -0.064]} rotation={[0.076, 0.557, 1.293]} scale={0.27}>
          <group>
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.Material} />
          <mesh name="Plane002_1" geometry={nodes.Plane002_1.geometry} material={new THREE.MeshStandardMaterial({map:useTexture(whatsapp)})} />
          <Text position={[-1.2,3,-1.5]} rotation={[1,3,1.5]} scale={[0.3,0.3,0.3]} intensity={3}>Whatsapp</Text>
          </group>
          <mesh name="Plane002_2" geometry={nodes.Plane002_2.geometry} material={materials.Material} />
          <group>
          <mesh name="Plane002_3" geometry={nodes.Plane002_3.geometry} material={new THREE.MeshStandardMaterial({map:useTexture(linkedIn)})} />
          <mesh name="Plane002_4" geometry={nodes.Plane002_4.geometry} material={materials.Material} />
          <Text position={[2,-8.5,-6]} rotation={[2.7,6.5,4.2]} scale={[0.3,0.3,0.3]} intensity={3}>Github</Text>
          </group>

          <mesh name="Plane002_5" geometry={nodes.Plane002_5.geometry} material={new THREE.MeshStandardMaterial({map:useTexture(instagram)})} />
          <mesh name="Plane002_6" geometry={nodes.Plane002_6.geometry} material={materials.Material} />
          <Text position={[1,1,9]} rotation={[1.8,-10,2]} scale={[0.3,0.3,0.3]} intensity={3}>LinkedIN</Text>
          <Text position={[7,-12,8]} rotation={[-2.9,1.6,2]} scale={[0.4,0.4,0.4]} intensity={3} color={'lightblue'}>Instagram</Text>
          <mesh name="Plane002_7" geometry={nodes.Plane002_7.geometry} material={new THREE.MeshStandardMaterial({map:useTexture(github)})} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Shipping.gltf')
