/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\model\AI-core.glb 
*/

import React, { useEffect } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export default function Aiorb(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/model/AI-core.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
  const controllerAnim = actions['AI_ControllerAction.001']
  const glowAnim = actions['Glow SphereAction.001']

  if (controllerAnim) {
    controllerAnim.reset().fadeIn(0.5).play()
  }

  if (glowAnim) {
    glowAnim.reset().fadeIn(0.5).play()
  }

  return () => {
    controllerAnim?.fadeOut(0.5)
    glowAnim?.fadeOut(0.5)
  }
}, [actions])
  return (
    <group ref={group} {...props} dispose={null} position={[0,-1.3,0]}>
      <group name="Scene">
        <group name="AI_Controller">
          <group name="particle_field" position={[0.021, 1.629, 0]} scale={1.5}>
            <mesh name="GN_Instance" geometry={nodes.GN_Instance.geometry} material={materials['Material.003']} position={[0.527, -0.468, -0.703]} scale={0.01} />
            <mesh name="GN_Instance_1" geometry={nodes.GN_Instance_1.geometry} material={materials['Material.003']} position={[0.282, -0.613, -0.729]} scale={0.01} />
            <mesh name="GN_Instance_2" geometry={nodes.GN_Instance_2.geometry} material={materials['Material.003']} position={[0.183, -0.421, -0.882]} scale={0.01} />
            <mesh name="GN_Instance_3" geometry={nodes.GN_Instance_3.geometry} material={materials['Material.003']} position={[0.061, -0.39, -0.912]} scale={0.01} />
            <mesh name="GN_Instance_4" geometry={nodes.GN_Instance_4.geometry} material={materials['Material.003']} position={[-0.128, -0.483, -0.859]} scale={0.01} />
            <mesh name="GN_Instance_5" geometry={nodes.GN_Instance_5.geometry} material={materials['Material.003']} position={[-0.186, -0.44, -0.871]} scale={0.01} />
            <mesh name="GN_Instance_6" geometry={nodes.GN_Instance_6.geometry} material={materials['Material.003']} position={[0.223, -0.235, -0.939]} scale={0.01} />
            <mesh name="GN_Instance_7" geometry={nodes.GN_Instance_7.geometry} material={materials['Material.003']} position={[0.116, -0.281, -0.945]} scale={0.01} />
            <mesh name="GN_Instance_8" geometry={nodes.GN_Instance_8.geometry} material={materials['Material.003']} position={[-0.458, -0.188, -0.862]} scale={0.01} />
            <mesh name="GN_Instance_9" geometry={nodes.GN_Instance_9.geometry} material={materials['Material.003']} position={[-0.165, -0.023, -0.983]} scale={0.01} />
            <mesh name="GN_Instance_10" geometry={nodes.GN_Instance_10.geometry} material={materials['Material.003']} position={[-0.297, -0.072, -0.945]} scale={0.01} />
            <mesh name="GN_Instance_11" geometry={nodes.GN_Instance_11.geometry} material={materials['Material.003']} position={[-0.234, -0.115, -0.958]} scale={0.01} />
            <mesh name="GN_Instance_12" geometry={nodes.GN_Instance_12.geometry} material={materials['Material.003']} position={[-0.453, -0.116, -0.876]} scale={0.01} />
            <mesh name="GN_Instance_13" geometry={nodes.GN_Instance_13.geometry} material={materials['Material.003']} position={[-0.387, -0.017, -0.917]} scale={0.01} />
            <mesh name="GN_Instance_14" geometry={nodes.GN_Instance_14.geometry} material={materials['Material.003']} position={[0.532, 0.054, -0.841]} scale={0.01} />
            <mesh name="GN_Instance_15" geometry={nodes.GN_Instance_15.geometry} material={materials['Material.003']} position={[0.367, 0.124, -0.917]} scale={0.01} />
            <mesh name="GN_Instance_16" geometry={nodes.GN_Instance_16.geometry} material={materials['Material.003']} position={[-0.15, 0.052, -0.982]} scale={0.01} />
            <mesh name="GN_Instance_17" geometry={nodes.GN_Instance_17.geometry} material={materials['Material.003']} position={[-0.212, 0.039, -0.971]} scale={0.01} />
            <mesh name="GN_Instance_18" geometry={nodes.GN_Instance_18.geometry} material={materials['Material.003']} position={[0.614, 0.206, -0.749]} scale={0.01} />
            <mesh name="GN_Instance_19" geometry={nodes.GN_Instance_19.geometry} material={materials['Material.003']} position={[0.49, 0.287, -0.818]} scale={0.01} />
            <mesh name="GN_Instance_20" geometry={nodes.GN_Instance_20.geometry} material={materials['Material.003']} position={[-0.292, 0.176, -0.936]} scale={0.01} />
            <mesh name="GN_Instance_21" geometry={nodes.GN_Instance_21.geometry} material={materials['Material.003']} position={[-0.212, 0.265, -0.933]} scale={0.01} />
            <mesh name="GN_Instance_22" geometry={nodes.GN_Instance_22.geometry} material={materials['Material.003']} position={[0.117, 0.396, -0.904]} scale={0.01} />
            <mesh name="GN_Instance_23" geometry={nodes.GN_Instance_23.geometry} material={materials['Material.003']} position={[-0.317, 0.474, -0.817]} scale={0.01} />
            <mesh name="GN_Instance_24" geometry={nodes.GN_Instance_24.geometry} material={materials['Material.003']} position={[-0.301, 0.566, -0.76]} scale={0.01} />
            <mesh name="GN_Instance_25" geometry={nodes.GN_Instance_25.geometry} material={materials['Material.003']} position={[-0.536, 0.517, -0.658]} scale={0.01} />
            <mesh name="GN_Instance_26" geometry={nodes.GN_Instance_26.geometry} material={materials['Material.003']} position={[-0.729, -0.667, -0.104]} scale={0.01} />
            <mesh name="GN_Instance_27" geometry={nodes.GN_Instance_27.geometry} material={materials['Material.003']} position={[-0.881, -0.438, -0.139]} scale={0.01} />
            <mesh name="GN_Instance_28" geometry={nodes.GN_Instance_28.geometry} material={materials['Material.003']} position={[-0.796, -0.184, -0.566]} scale={0.01} />
            <mesh name="GN_Instance_29" geometry={nodes.GN_Instance_29.geometry} material={materials['Material.003']} position={[-0.859, -0.225, -0.443]} scale={0.01} />
            <mesh name="GN_Instance_30" geometry={nodes.GN_Instance_30.geometry} material={materials['Material.003']} position={[-0.965, -0.224, -0.065]} scale={0.01} />
            <mesh name="GN_Instance_31" geometry={nodes.GN_Instance_31.geometry} material={materials['Material.003']} position={[-0.965, -0.23, 0.052]} scale={0.01} />
            <mesh name="GN_Instance_32" geometry={nodes.GN_Instance_32.geometry} material={materials['Material.003']} position={[-0.92, -0.346, 0.178]} scale={0.01} />
            <mesh name="GN_Instance_33" geometry={nodes.GN_Instance_33.geometry} material={materials['Material.003']} position={[-0.92, -0.12, -0.362]} scale={0.01} />
            <mesh name="GN_Instance_34" geometry={nodes.GN_Instance_34.geometry} material={materials['Material.003']} position={[-0.981, -0.099, -0.115]} scale={0.01} />
            <mesh name="GN_Instance_35" geometry={nodes.GN_Instance_35.geometry} material={materials['Material.003']} position={[-0.987, 0.094, -0.054]} scale={0.01} />
            <mesh name="GN_Instance_36" geometry={nodes.GN_Instance_36.geometry} material={materials['Material.003']} position={[-0.982, 0.126, -0.08]} scale={0.01} />
            <mesh name="GN_Instance_37" geometry={nodes.GN_Instance_37.geometry} material={materials['Material.003']} position={[-0.99, 0.105, 0.006]} scale={0.01} />
            <mesh name="GN_Instance_38" geometry={nodes.GN_Instance_38.geometry} material={materials['Material.003']} position={[-0.921, 0.326, 0.194]} scale={0.01} />
            <mesh name="GN_Instance_39" geometry={nodes.GN_Instance_39.geometry} material={materials['Material.003']} position={[-0.827, 0.469, 0.292]} scale={0.01} />
            <mesh name="GN_Instance_40" geometry={nodes.GN_Instance_40.geometry} material={materials['Material.003']} position={[-0.657, 0.48, -0.567]} scale={0.01} />
            <mesh name="GN_Instance_41" geometry={nodes.GN_Instance_41.geometry} material={materials['Material.003']} position={[-0.645, 0.628, 0.433]} scale={0.01} />
            <mesh name="GN_Instance_42" geometry={nodes.GN_Instance_42.geometry} material={materials['Material.003']} position={[-0.393, -0.57, 0.711]} scale={0.01} />
            <mesh name="GN_Instance_43" geometry={nodes.GN_Instance_43.geometry} material={materials['Material.003']} position={[-0.198, -0.659, 0.717]} scale={0.01} />
            <mesh name="GN_Instance_44" geometry={nodes.GN_Instance_44.geometry} material={materials['Material.003']} position={[-0.029, -0.687, 0.72]} scale={0.01} />
            <mesh name="GN_Instance_45" geometry={nodes.GN_Instance_45.geometry} material={materials['Material.003']} position={[-0.019, -0.541, 0.837]} scale={0.01} />
            <mesh name="GN_Instance_46" geometry={nodes.GN_Instance_46.geometry} material={materials['Material.003']} position={[-0.417, -0.456, 0.779]} scale={0.01} />
            <mesh name="GN_Instance_47" geometry={nodes.GN_Instance_47.geometry} material={materials['Material.003']} position={[-0.325, -0.448, 0.828]} scale={0.01} />
            <mesh name="GN_Instance_48" geometry={nodes.GN_Instance_48.geometry} material={materials['Material.003']} position={[-0.514, -0.214, 0.827]} scale={0.01} />
            <mesh name="GN_Instance_49" geometry={nodes.GN_Instance_49.geometry} material={materials['Material.003']} position={[0.169, -0.272, 0.943]} scale={0.01} />
            <mesh name="GN_Instance_50" geometry={nodes.GN_Instance_50.geometry} material={materials['Material.003']} position={[0.306, -0.277, 0.904]} scale={0.01} />
            <mesh name="GN_Instance_51" geometry={nodes.GN_Instance_51.geometry} material={materials['Material.003']} position={[-0.519, 0.09, 0.846]} scale={0.01} />
            <mesh name="GN_Instance_52" geometry={nodes.GN_Instance_52.geometry} material={materials['Material.003']} position={[0.222, 0.032, 0.969]} scale={0.01} />
            <mesh name="GN_Instance_53" geometry={nodes.GN_Instance_53.geometry} material={materials['Material.003']} position={[0.283, 0.248, 0.918]} scale={0.01} />
            <mesh name="GN_Instance_54" geometry={nodes.GN_Instance_54.geometry} material={materials['Material.003']} position={[-0.643, 0.318, 0.689]} scale={0.01} />
            <mesh name="GN_Instance_55" geometry={nodes.GN_Instance_55.geometry} material={materials['Material.003']} position={[-0.09, 0.512, 0.849]} scale={0.01} />
            <mesh name="GN_Instance_56" geometry={nodes.GN_Instance_56.geometry} material={materials['Material.003']} position={[0.264, 0.459, 0.84]} scale={0.01} />
            <mesh name="GN_Instance_57" geometry={nodes.GN_Instance_57.geometry} material={materials['Material.003']} position={[-0.457, 0.594, 0.654]} scale={0.01} />
            <mesh name="GN_Instance_58" geometry={nodes.GN_Instance_58.geometry} material={materials['Material.003']} position={[0.23, 0.584, 0.768]} scale={0.01} />
            <mesh name="GN_Instance_59" geometry={nodes.GN_Instance_59.geometry} material={materials['Material.003']} position={[0.678, -0.528, 0.499]} scale={0.01} />
            <mesh name="GN_Instance_60" geometry={nodes.GN_Instance_60.geometry} material={materials['Material.003']} position={[0.704, -0.59, 0.377]} scale={0.01} />
            <mesh name="GN_Instance_61" geometry={nodes.GN_Instance_61.geometry} material={materials['Material.003']} position={[0.767, -0.631, -0.012]} scale={0.01} />
            <mesh name="GN_Instance_62" geometry={nodes.GN_Instance_62.geometry} material={materials['Material.003']} position={[0.674, -0.631, -0.367]} scale={0.01} />
            <mesh name="GN_Instance_63" geometry={nodes.GN_Instance_63.geometry} material={materials['Material.003']} position={[0.8, -0.351, 0.477]} scale={0.01} />
            <mesh name="GN_Instance_64" geometry={nodes.GN_Instance_64.geometry} material={materials['Material.003']} position={[0.907, -0.385, -0.143]} scale={0.01} />
            <mesh name="GN_Instance_65" geometry={nodes.GN_Instance_65.geometry} material={materials['Material.003']} position={[0.796, -0.446, -0.389]} scale={0.01} />
            <mesh name="GN_Instance_66" geometry={nodes.GN_Instance_66.geometry} material={materials['Material.003']} position={[0.708, -0.462, -0.526]} scale={0.01} />
            <mesh name="GN_Instance_67" geometry={nodes.GN_Instance_67.geometry} material={materials['Material.003']} position={[0.722, -0.317, -0.604]} scale={0.01} />
            <mesh name="GN_Instance_68" geometry={nodes.GN_Instance_68.geometry} material={materials['Material.003']} position={[0.885, -0.262, 0.37]} scale={0.01} />
            <mesh name="GN_Instance_69" geometry={nodes.GN_Instance_69.geometry} material={materials['Material.003']} position={[0.886, -0.226, -0.388]} scale={0.01} />
            <mesh name="GN_Instance_70" geometry={nodes.GN_Instance_70.geometry} material={materials['Material.003']} position={[0.934, -0.049, 0.343]} scale={0.01} />
            <mesh name="GN_Instance_71" geometry={nodes.GN_Instance_71.geometry} material={materials['Material.003']} position={[0.971, -0.081, -0.2]} scale={0.01} />
            <mesh name="GN_Instance_72" geometry={nodes.GN_Instance_72.geometry} material={materials['Material.003']} position={[0.862, 0.12, 0.48]} scale={0.01} />
            <mesh name="GN_Instance_73" geometry={nodes.GN_Instance_73.geometry} material={materials['Material.003']} position={[0.865, 0.026, -0.491]} scale={0.01} />
            <mesh name="GN_Instance_74" geometry={nodes.GN_Instance_74.geometry} material={materials['Material.003']} position={[0.868, 0.223, 0.424]} scale={0.01} />
            <mesh name="GN_Instance_75" geometry={nodes.GN_Instance_75.geometry} material={materials['Material.003']} position={[0.941, 0.277, 0.171]} scale={0.01} />
            <mesh name="GN_Instance_76" geometry={nodes.GN_Instance_76.geometry} material={materials['Material.003']} position={[0.973, 0.187, -0.098]} scale={0.01} />
            <mesh name="GN_Instance_77" geometry={nodes.GN_Instance_77.geometry} material={materials['Material.003']} position={[0.901, 0.276, -0.318]} scale={0.01} />
            <mesh name="GN_Instance_78" geometry={nodes.GN_Instance_78.geometry} material={materials['Material.003']} position={[0.924, 0.266, -0.244]} scale={0.01} />
            <mesh name="GN_Instance_79" geometry={nodes.GN_Instance_79.geometry} material={materials['Material.003']} position={[0.771, 0.212, -0.588]} scale={0.01} />
            <mesh name="GN_Instance_80" geometry={nodes.GN_Instance_80.geometry} material={materials['Material.003']} position={[0.744, 0.256, -0.604]} scale={0.01} />
            <mesh name="GN_Instance_81" geometry={nodes.GN_Instance_81.geometry} material={materials['Material.003']} position={[0.802, 0.46, 0.364]} scale={0.01} />
            <mesh name="GN_Instance_82" geometry={nodes.GN_Instance_82.geometry} material={materials['Material.003']} position={[0.738, 0.663, -0.048]} scale={0.01} />
            <mesh name="GN_Instance_83" geometry={nodes.GN_Instance_83.geometry} material={materials['Material.003']} position={[0.772, 0.581, -0.224]} scale={0.01} />
            <mesh name="GN_Instance_84" geometry={nodes.GN_Instance_84.geometry} material={materials['Material.003']} position={[0.701, 0.624, -0.327]} scale={0.01} />
            <mesh name="GN_Instance_85" geometry={nodes.GN_Instance_85.geometry} material={materials['Material.003']} position={[0.673, 0.462, -0.568]} scale={0.01} />
            <mesh name="GN_Instance_86" geometry={nodes.GN_Instance_86.geometry} material={materials['Material.003']} position={[-0.238, -0.765, 0.582]} scale={0.01} />
            <mesh name="GN_Instance_87" geometry={nodes.GN_Instance_87.geometry} material={materials['Material.003']} position={[-0.34, -0.779, 0.52]} scale={0.01} />
            <mesh name="GN_Instance_88" geometry={nodes.GN_Instance_88.geometry} material={materials['Material.003']} position={[0.499, -0.738, 0.445]} scale={0.01} />
            <mesh name="GN_Instance_89" geometry={nodes.GN_Instance_89.geometry} material={materials['Material.003']} position={[0.186, -0.877, 0.428]} scale={0.01} />
            <mesh name="GN_Instance_90" geometry={nodes.GN_Instance_90.geometry} material={materials['Material.003']} position={[0.14, -0.84, 0.52]} scale={0.01} />
            <mesh name="GN_Instance_91" geometry={nodes.GN_Instance_91.geometry} material={materials['Material.003']} position={[0.486, -0.868, 0.017]} scale={0.01} />
            <mesh name="GN_Instance_92" geometry={nodes.GN_Instance_92.geometry} material={materials['Material.003']} position={[-0.119, -0.984, 0.056]} scale={0.01} />
            <mesh name="GN_Instance_93" geometry={nodes.GN_Instance_93.geometry} material={materials['Material.003']} position={[0.296, -0.947, -0.044]} scale={0.01} />
            <mesh name="GN_Instance_94" geometry={nodes.GN_Instance_94.geometry} material={materials['Material.003']} position={[-0.489, -0.856, -0.139]} scale={0.01} />
            <mesh name="GN_Instance_95" geometry={nodes.GN_Instance_95.geometry} material={materials['Material.003']} position={[-0.636, -0.756, -0.076]} scale={0.01} />
            <mesh name="GN_Instance_96" geometry={nodes.GN_Instance_96.geometry} material={materials['Material.003']} position={[-0.225, -0.88, -0.402]} scale={0.01} />
            <mesh name="GN_Instance_97" geometry={nodes.GN_Instance_97.geometry} material={materials['Material.003']} position={[-0.613, -0.658, -0.432]} scale={0.01} />
            <mesh name="GN_Instance_98" geometry={nodes.GN_Instance_98.geometry} material={materials['Material.003']} position={[0.422, -0.655, -0.621]} scale={0.01} />
            <mesh name="GN_Instance_99" geometry={nodes.GN_Instance_99.geometry} material={materials['Material.003']} position={[-0.007, -0.74, -0.664]} scale={0.01} />
            <mesh name="GN_Instance_100" geometry={nodes.GN_Instance_100.geometry} material={materials['Material.003']} position={[-0.507, -0.619, -0.592]} scale={0.01} />
            <mesh name="GN_Instance_101" geometry={nodes.GN_Instance_101.geometry} material={materials['Material.003']} position={[0.443, 0.681, -0.575]} scale={0.01} />
            <mesh name="GN_Instance_102" geometry={nodes.GN_Instance_102.geometry} material={materials['Material.003']} position={[0.284, 0.709, -0.639]} scale={0.01} />
            <mesh name="GN_Instance_103" geometry={nodes.GN_Instance_103.geometry} material={materials['Material.003']} position={[-0.508, 0.611, -0.599]} scale={0.01} />
            <mesh name="GN_Instance_104" geometry={nodes.GN_Instance_104.geometry} material={materials['Material.003']} position={[0.632, 0.705, -0.307]} scale={0.01} />
            <mesh name="GN_Instance_105" geometry={nodes.GN_Instance_105.geometry} material={materials['Material.003']} position={[0.351, 0.792, -0.493]} scale={0.01} />
            <mesh name="GN_Instance_106" geometry={nodes.GN_Instance_106.geometry} material={materials['Material.003']} position={[0.255, 0.88, -0.383]} scale={0.01} />
            <mesh name="GN_Instance_107" geometry={nodes.GN_Instance_107.geometry} material={materials['Material.003']} position={[0.165, 0.906, -0.382]} scale={0.01} />
            <mesh name="GN_Instance_108" geometry={nodes.GN_Instance_108.geometry} material={materials['Material.003']} position={[-0.216, 0.851, -0.463]} scale={0.01} />
            <mesh name="GN_Instance_109" geometry={nodes.GN_Instance_109.geometry} material={materials['Material.003']} position={[-0.338, 0.841, -0.41]} scale={0.01} />
            <mesh name="GN_Instance_110" geometry={nodes.GN_Instance_110.geometry} material={materials['Material.003']} position={[0.024, 0.978, -0.191]} scale={0.01} />
            <mesh name="GN_Instance_111" geometry={nodes.GN_Instance_111.geometry} material={materials['Material.003']} position={[0.255, 0.959, -0.043]} scale={0.01} />
            <mesh name="GN_Instance_112" geometry={nodes.GN_Instance_112.geometry} material={materials['Material.003']} position={[-0.544, 0.833, -0.04]} scale={0.01} />
            <mesh name="GN_Instance_113" geometry={nodes.GN_Instance_113.geometry} material={materials['Material.003']} position={[0.21, 0.974, 0.011]} scale={0.01} />
            <mesh name="GN_Instance_114" geometry={nodes.GN_Instance_114.geometry} material={materials['Material.003']} position={[0.016, 0.998, 0.012]} scale={0.01} />
            <mesh name="GN_Instance_115" geometry={nodes.GN_Instance_115.geometry} material={materials['Material.003']} position={[-0.413, 0.902, 0.041]} scale={0.01} />
            <mesh name="GN_Instance_116" geometry={nodes.GN_Instance_116.geometry} material={materials['Material.003']} position={[0.36, 0.872, 0.322]} scale={0.01} />
            <mesh name="GN_Instance_117" geometry={nodes.GN_Instance_117.geometry} material={materials['Material.003']} position={[-0.05, 0.953, 0.275]} scale={0.01} />
            <mesh name="GN_Instance_118" geometry={nodes.GN_Instance_118.geometry} material={materials['Material.003']} position={[-0.226, 0.952, 0.184]} scale={0.01} />
            <mesh name="GN_Instance_119" geometry={nodes.GN_Instance_119.geometry} material={materials['Material.003']} position={[0.071, 0.871, 0.47]} scale={0.01} />
            <mesh name="GN_Instance_120" geometry={nodes.GN_Instance_120.geometry} material={materials['Material.003']} position={[0.294, 0.712, 0.63]} scale={0.01} />
          </group>
          <mesh name="Glow_Sphere" geometry={nodes.Glow_Sphere.geometry} material={materials['Material.005']} rotation={[0, -0.021, 0]} scale={1.348} />
          <mesh name="inner_glow_sphere" geometry={nodes.inner_glow_sphere.geometry} material={materials['Mini Inner Sphere.001']} position={[0.021, 1.629, 0]} scale={0.092} />
          <mesh name="inner_glow_sphere001" geometry={nodes.inner_glow_sphere001.geometry} material={materials['middle sphere']} position={[0.021, 1.629, 0]} scale={0.578} />
        </group>
        <group name="Area" position={[-0.348, -0.139, -0.22]} rotation={[1.766, -0.069, -0.522]} />
        <pointLight name="zLight" intensity={51.413} decay={2} position={[4.076, 5.904, -1.005]} rotation={[-1.839, 0.602, 1.932]} />
        <PerspectiveCamera name="Camera" makeDefault={false} far={100} near={0.1} fov={21.239} position={[7.359, 4.958, 6.926]} rotation={[-0.627, 0.71, 0.441]} />
        <mesh name="FinalBaseMesh" geometry={nodes.FinalBaseMesh.geometry} material={nodes.FinalBaseMesh.material} position={[-4.38, 6.558, 1.2]} rotation={[-1.501, -1.009, 2.996]} scale={0.684} />
        <mesh name="Torus" geometry={nodes.Torus.geometry} material={materials['Material.002']} position={[0.021, 1.629, 0]} rotation={[0.934, -0.908, -2.379]} scale={[0.095, 0.25, 0.095]} />
        <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={materials['Material.004']} position={[0.021, 1.629, 0]} rotation={[0.084, -0.027, 0.331]} scale={[0.098, 0.294, 0.094]} />
        <mesh name="Torus002" geometry={nodes.Torus002.geometry} material={materials['Material.002']} position={[0.063, 1.645, 0.017]} rotation={[-2.517, -0.136, 2.826]} scale={[0.094, 0.294, 0.094]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/AI-core.glb')
