/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Home_interface.gltf 
*/

import React from 'react'
import { motion } from 'framer-motion-3d'
import { useGLTF, useTexture, ScrollControls } from '@react-three/drei'
import vara from '../../assets/Vara.jpg'
import * as THREE from 'three'
export default function Home_interface(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Home_interface.gltf')
  const Vara=useTexture(vara);
  return (
    <motion.group 
    ref={group} 
    {...props} 
    dispose={null}
    transition={{
      name:'spring',
      mass:5,
      stiffness:100,
      damping:5,
      restDelta:0.0001,
      duration:3,
      delay:0,
    }}
    initial={{
      opacity:0,
      scale:0,
      y:25,
      rotate:-Math.PI/4
    }}
    animate={{
      opacity:1,
      scale:1,
      y:0,
    }}
    >
      <group name="Scene" position={[0,-2,3]} rotation={[0,-Math.PI/4,Math.PI/230]}>
        <group name="Scene_Collection" />
        <group name="Collection" />
        <pointLight name="Light" intensity={200.413} decay={2} position={[3.088, 6.626, -1.13]} rotation={[-1.839, 0.602, 1.932]} />
        {/* <PerspectiveCamera name="Camera" makeDefault={false} far={100} near={0.1} fov={39.598} position={[9.887, 18.653, 9.573]} rotation={[-1.118, 0.542, 0.815]} /> */}
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.010']} position={[-0.989, 0.722, -0.124]} scale={[2, 1.531, 2]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.009']} position={[0.656, 0.979, -0.124]} scale={[0.287, 1.531, 1.98]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.006']} position={[-0.597, 1.11, 0.306]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.004']} position={[-1.045, 1.182, -1.406]} scale={[1.051, 0.095, 0.564]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.007']} position={[-0.874, 1.138, -1.406]} scale={[0.872, 0.095, 0.564]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.005']} position={[-1.308, 3.323, -0.363]} scale={[-2.182, -2.535, -2.13]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.013']} position={[-0.953, 3.136, -0.086]} scale={[-2.182, -2.535, -2.13]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.011']} position={[-2.241, 1.56, 0.808]} scale={0.404} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.012']} position={[-1.394, 3.136, -0.086]} scale={[-2.182, -2.535, -2.13]} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Material.008']} position={[-1.944, 1.301, -1.372]} scale={[0.142, 0.067, 0.239]} />
        <group name="Myself003" position={[-0.791, -0.246, -0.3]}>
          <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.014']} />
          <mesh name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={new THREE.MeshStandardMaterial({map:Vara})} />
          
        </group>
        <group name="Cube003" position={[-3.291, 3.45, 0.394]} scale={0.13}>
          <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials['Material.017']} />
          <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials['Material.018']} />
        </group>
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.019']} position={[-3.276, 3.503, -0.499]} scale={[0.169, 0.169, 0.045]} />
        <group name="Sphere001" position={[-0.49, 1.117, 1.307]} scale={-13.65}>
          <mesh name="Sphere004" geometry={nodes.Sphere004.geometry} material={materials.Glassy} />
          {/* <mesh name="Sphere004_1" geometry={nodes.Sphere004_1.geometry} material={materials.Ground} /> */}
        </group>
      </group>
    </motion.group>
  )
}

useGLTF.preload('/Home_interface.gltf')
